[package]
name = "shelby_time_capsule"
version = "1.0.0"
authors = ["Tolu"]

[addresses]
shelby_capsule = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
